[package]
name = "qtpl_tests"
version = "0.3.0"
authors = ["Naitik Shah <n@daaku.org>"]
edition = "2018"
publish = false
repository = "https://github.com/daaku/qtpl"

[dependencies]
qtpl = { path = "../qtpl" }
v_htmlescape = "0.8"

[dev-dependencies]
pretty_assertions = "0.6"
