[package]
name = "qtpl_tests"
version = "0.5.1"
authors = ["Naitik Shah <n@daaku.org>"]
edition = "2018"
publish = false
repository = "https://github.com/daaku/qtpl"

[dependencies]
qtpl = { path = "../qtpl" }

[dev-dependencies]
pretty_assertions = "0.6"
